### PR TITLE
add openpgp encryption middleware

### PR DESCRIPTION
**Pull request by dhia-gharsallaoui**

### CODE REVIEW

**Comment by wneessen** [comment]
Thanks for the PR Dhia! A few notes:

- Could you please write test coverage for the PR?
- I am wondering if it would make sense to offer different types of actions: encryption-only, signature-only, encrpyt and sign?
- The logs should go to os.Stderr in my opinion. Does your loggigng library offer this or would it make sense to just use stdlib log? Is JSON logging really preferable for this?

**Comment by dhia-gharsallaoui** [comment]
Thank your for your fast interaction!


> * Could you please write test coverage for the PR?

I will work on it soon when I have free time.



> * I am wondering if it would make sense to offer different types of actions: encryption-only, signature-only, encrpyt and sign?

I don't know as I didn't seen use cases that need only one.



> * The logs should go to os.Stderr in my opinion. Does your loggigng library offer this or would it make sense to just use stdlib log? Is JSON logging really preferable for this?

the Middleware use the [log interface](https://github.com/dhia-gharsallaoui/go-logger/blob/main/log.go#L23)  so you can inject your logger either JSON or anything Else. In case you didn't inject one he will use the JSON logger as default wich use [os.Stderr](https://github.com/dhia-gharsallaoui/go-logger/blob/main/jsonlog.go#L33 ) dependening on the verbosity.

**Comment by wneessen** [comment]
> > * Could you please write test coverage for the PR?
> I will work on it soon when I have free time.
> 
Great, thanks!

> > * I am wondering if it would make sense to offer different types of actions: encryption-only, signature-only, encrpyt and sign? 
> I don't know as I didn't seen use cases that need only one.
> 
Understood. Then let's start with encryption first and we can later add mail signing.

> > * The logs should go to os.Stderr in my opinion. Does your loggigng library offer this or would it make sense to just use stdlib log? Is JSON logging really preferable for this?
> the Middleware use the [log interface](https://github.com/dhia-gharsallaoui/go-logger/blob/main/log.go#L23) so you can inject your logger either JSON or anything Else. In case you didn't inject one he will use the JSON logger as default wich use [os.Stderr](https://github.com/dhia-gharsallaoui/go-logger/blob/main/jsonlog.go#L33) dependening on the verbosity.

That makes sense.

**Comment by wneessen** [comment]
Hi @dhia-gharsallaoui, I'm gonna merge this for now, even with the missing tests. I'd like to contribute to this package. This way we can both work on the code. If I find some time, I'll add some tests as well, if that's ok with you.

**Pull request merged**
